Snapshot with error messages
[xUnit.net 00:00:00.13]   Finished:    Rockaway.WebApp.Tests
  Rockaway.WebApp.Tests test net10.0 failed with 1 error(s) (0.6s)
    D:\workshops\rockaway-202604\Rockaway.WebApp.Tests\UnitTest1.cs(10): error TESTERROR:
      Rockaway.WebApp.Tests.UnitTest1.Index_Page_Returns_Success (6ms): Error Message: System.InvalidOperationExceptio
      n : Can't find 'D:\workshops\rockaway-202604\Rockaway.WebApp.Tests\bin\Debug\net10.0\testhost.deps.json'. This f
      ile is required for functional tests to run properly. There should be a copy of the file on your source project
      bin folder. If that is not the case, make sure that the property PreserveCompilationContext is set to true on yo
      ur project file. E.g '<PreserveCompilationContext>true</PreserveCompilationContext>'. For functional tests to wo
      rk they need to either run from the build output folder or the testhost.deps.json file from your application's o
      utput directory must be copied to the folder where the tests are running on. A common cause for this error is ha
      ving shadow copying enabled when the tests run.
      Stack Trace:
         at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureDepsFile()
         at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.StartServer()
         at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
         at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHa
      ndler[] handlers)
         at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions o
      ptions)
         at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient()
         at Rockaway.WebApp.Tests.UnitTest1.Index_Page_Returns_Success() in D:\workshops\rockaway-202604\Rockaway.WebA
      pp.Tests\UnitTest1.cs:line 10
         at Rockaway.WebApp.Tests.UnitTest1.Index_Page_Returns_Success() in D:\workshops\rockaway-202604\Rockaway.WebA
      pp.Tests\UnitTest1.cs:line 12